language: node_js

node_js:
  - "10.16.0"

services:
  - mongodb
  - docker

cache:
  timeout: 1000
  directories:
    - $HOME/.npm-cache
    - $HOME/.npm-prefix
    - $HOME/.npm

matrix:
  fast_finish: true
  include:
    - env: server
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/server
        - npm install
        - npm install codecov -g
      script:
        - npm run test:cov
        - codecov
        - npm run build
      deploy:
        provider: script
        script: bash release-docker/release.sh
        on:
          branch: master
    - env: web
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/web
        - npm install
      script:
        - NODE_OPTIONS=--max_old_space_size=1024 CI=false npm run build
      deploy:
        provider: script
        script: bash release-docker/release.sh
        on:
          branch: master
    - env: admin
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/admin
        - npm install
      script:
        - CI=false npm run build
      deploy:
        provider: script
        script: bash release-docker/release.sh
        on:
          branch: master
    - env: nginx
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/nginx
      script:
        - set -e 
        - docker build -f Dockerfile -t bs32g1038/nginx:test .
        - docker run -d bs32g1038/nginx:test
        - sleep 8
        - docker stop $(docker ps -a -q)
      deploy:
        provider: script
        script: bash release-docker-image.sh
        on:
          branch: master