language: node_js

node_js: stable

services:
  - mongodb

cache: yarn
cache: npm

install:
  - cd $TRAVIS_BUILD_DIR
  - npm install -g codecov
  - bash scripts/install-dependencies.sh || travis_terminate 1

before_script:
  - sleep 15
  - git config --global user.name "bs32g1038"
  - git config --global user.email "bs32g1038@163.com"

script:
  - cd $TRAVIS_BUILD_DIR
  - bash scripts/build.sh || travis_terminate 1

after_success:
  - cd $TRAVIS_BUILD_DIR
  - bash scripts/after_success.sh || travis_terminate 1

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/bs32g1038/node-blog.git