FROM node:8.11.1-alpine
RUN apk add --update \
  --repository http://dl-3.alpinelinux.org/alpine/edge/testing \
  vips-tools \
  && rm -rf /var/cache/apk/*
WORKDIR /code
COPY ./package.json /code
RUN npm install --production
COPY . /code