export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_GUESTBOOKS = 'FETCH_GUESTBOOKS';
export const FETCH_LINKS = 'FETCH_LINKS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const IS_MOBILE = 'IS_MOBILE';

export const FETCH_ABOUT_USER_PROFILE = 'FETCH_ABOUT_USER_PROFILE';
export const CHECK_ABOUT_USER_STATUS = 'CHECK_ABOUT_USER_STATUS';
