export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_RECENT_ARTICLES = 'FETCH_RECENT_ARTICLES';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_GUESTBOOKS = 'FETCH_GUESTBOOKS';
export const FETCH_LINKS = 'FETCH_LINKS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const IS_MOBILE = 'IS_MOBILE';
