/*
 * @Author =bs32g1038@163.com 
 * @Date =2017-03-13 14:33:58 
 * @Last Modified by: bs32g1038@163.com
 * @Last Modified time: 2017-03-15 13:29:35
 */

export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';
export const REQUEST_SAVE_ARTICLE = 'REQUEST_SAVE_ARTICLE';

export const RECEIVE_SAVE_ARTICLE = 'RECEIVE_SAVE_ARTICLE';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const VISIBLE = 'VISIBLE'
export const PAGINATION = 'PAGINATION';
export const SELECTED_ROW_KEYS = 'ARTICLE/SELECTED_ROW_KEYS';
export const LOADING = 'LOADING';
export const ARTICLE_CATEGORIES = 'ARTICLE/ARTICLE_CATEGORIES';


/**
 * 分类
 */

export const REQUEST_CATEGORYS = 'REQUEST_CATEGORYS';
export const RECEIVE_CATEGORYS = 'RECEIVE_CATEGORYS';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';

/**
 * 评论
 */
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const REPLY_COMMENT = 'REPLY_COMMENT';
export const UPDATE_COMMENT_PASS = 'UPDATE_COMMENT_PASS'

/**
 * 留言
 */
export const REQUEST_GUESTBOOKS = 'REQUEST_GUESTBOOKS';
export const RECEIVE_GUESTBOOKS = 'RECEIVE_GUESTBOOKS';
export const REPLY_GUESTBOOK = 'REPLY_GUESTBOOK'
export const DELETE_GUESTBOOK = 'DELETE_GUESTBOOK';
export const UPDATE_GUESTBOOK_PASS = 'UPDATE_GUESTBOOK_PASS';


/**
 * 链接
 */
export const REQUEST_LINKS = 'REQUEST_LINKS';
export const RECEIVE_LINKS = 'RECEIVE_LINKS';
export const DELETE_LINK = 'DELETE_LINK';
export const SAVE_LINK = 'SAVE_LINK';